apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-c2
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: mgmt
    repoURL: 'https://github.com/tanwar57/workshop-api.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-c2.yaml
  project: default
